name: Python package Lint+Test+Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: "latest"
          enable-cache: true

      - name: Prepare the project
        shell: bash
        run: uv sync --extra dev --extra tests --verbose

      - name: Minimize uv cache
        shell: bash
        run: uv cache prune --ci

      - name: Lint
        shell: bash
        run: make lint

      - name: Test
        shell: bash
        run: make test

      - name: Build the package
        shell: bash
        run: uv build --wheel

      - name: Verify wheel installation
        shell: bash
        run: |
          for wheel in dist/*.whl; do
            uv run --verbose --with $wheel --no-project --refresh-package machine2human -- python -c "import m2h; print(m2h.__version__)"
          done
