name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  build:
    name: 📦 Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          version: "latest"
          enable-cache: true

      - name: Prepare the project
        shell: bash
        run: uv sync --extra dev --extra tests --verbose

      - name: Minimize uv cache
        run: uv cache prune --ci

      - name: Build wheels
        shell: bash
        run: |
          uv build --wheel

      - name: Verify wheel installation
        shell: bash
        run: |
          for wheel in dist/*.whl; do
            uv run --verbose --with $wheel --no-project --refresh-package machine2human -- python -c "import m2h; print(m2h.__version__)"
          done

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: m2h-${{ matrix.os }}-${{ github.run_id }}
          if-no-files-found: error
          compression-level: 9
          path: |
            dist/*.whl
            dist/*.tar.gz

  publish:
    name: 🐍 Publish distribution 📦
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List artifacts
        run: ls -la dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
